spring.application.name=careerflow
spring.datasource.url=jdbc:postgresql://localhost:5432/careerflow
spring.datasource.username=gamzeuver
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true